from pwn import *
r = remote("ssh.challs.olicyber.it", 34009) # esplorata prima a mano
r.recv()
r.sendline(b"gabibbo")
r.recv()
r.sendline(b"p4ssw0rd_SSH_s3gr3t4")
r.recv()
r.sendline(b"cd Desktop")
r.recv()
r.sendline(b"cd olicyber")
r.recv()
r.sendline(b"cd 2022")
r.recv()
r.sendline(b"cd Olicyber_git_repository_2022")
r.recv()
r.sendline(b"cd network_brutta")
r.recv()
r.sendline(b"cat flag.txt")
r.recv()
print(r.recvuntil(b"}").decode())